language: c

before_install:
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -qq mono-devel mono-gmcs > /dev/null
  - mozroots --import --sync
  - mv -f src/.nuget/NuGet.targets-mono src/.nuget/NuGet.targets
  - chmod +x lib/xunit/xunit.console.clr4.x86.exe
  - export EnableNuGetPackageRestore=true

script:
  - cd src/
  - xbuild IsThisOn.sln
  - mono ../lib/xunit/xunit.console.clr4.x86.exe IsThisOn.Tests/bin/Debug/IsThisOn.Tests.dll